// This file will be generated by Supabase CLI
// For now, we'll create a basic structure

export interface Database {
  public: {
    Tables: {
      terminals: {
        Row: {
          id: string;
          name: string;
          code: string;
          capacity: number;
          timezone: string;
          status: string;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          code: string;
          capacity: number;
          timezone?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          code?: string;
          capacity?: number;
          timezone?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      vessels: {
        Row: {
          id: string;
          name: string;
          eta: string;
          terminal_id: string;
          status: string;
          container_count: number;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          eta: string;
          terminal_id: string;
          status?: string;
          container_count: number;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          eta?: string;
          terminal_id?: string;
          status?: string;
          container_count?: number;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      containers: {
        Row: {
          id: string;
          cntr_no: string;
          type: string;
          line: string;
          ready_at: string | null;
          hold: boolean;
          status: string;
          terminal_id: string;
          vessel_id: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          cntr_no: string;
          type: string;
          line: string;
          ready_at?: string | null;
          hold?: boolean;
          status?: string;
          terminal_id: string;
          vessel_id?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          cntr_no?: string;
          type?: string;
          line?: string;
          ready_at?: string | null;
          hold?: boolean;
          status?: string;
          terminal_id?: string;
          vessel_id?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      slots: {
        Row: {
          id: string;
          terminal_id: string;
          window_start: string;
          window_end: string;
          capacity: number;
          booked: number;
          status: string;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          terminal_id: string;
          window_start: string;
          window_end: string;
          capacity: number;
          booked?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          terminal_id?: string;
          window_start?: string;
          window_end?: string;
          capacity?: number;
          booked?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      drivers: {
        Row: {
          id: string;
          name: string;
          phone: string | null;
          email: string | null;
          status: string;
          license_number: string;
          license_expiry: string;
          carrier_id: string;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          phone?: string | null;
          email?: string | null;
          status?: string;
          license_number: string;
          license_expiry: string;
          carrier_id: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          phone?: string | null;
          email?: string | null;
          status?: string;
          license_number?: string;
          license_expiry?: string;
          carrier_id?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      trips: {
        Row: {
          id: string;
          driver_id: string;
          container_id: string;
          pickup_slot_id: string | null;
          return_empty: boolean;
          status: string;
          eta: string | null;
          started_at: string | null;
          completed_at: string | null;
          turn_minutes: number | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          driver_id: string;
          container_id: string;
          pickup_slot_id?: string | null;
          return_empty?: boolean;
          status?: string;
          eta?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          turn_minutes?: number | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          driver_id?: string;
          container_id?: string;
          pickup_slot_id?: string | null;
          return_empty?: boolean;
          status?: string;
          eta?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          turn_minutes?: number | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
